### ISSUE TITLE
SPで昔のサムネを表示すると上揃いになっている

### ISSUE THREAD

**Issue by naari3** [naari3/otomad-search#35]
## 現在の状況
![image](https://user-images.githubusercontent.com/12756563/100179621-c45c4000-2f19-11eb-89f3-ea5027680528.png)
## 期待するものの参考
![image](https://user-images.githubusercontent.com/12756563/100179671-d50cb600-2f19-11eb-87cb-9de810c21c22.png)

**Comment by gokulin** [comment]
.Thumbnail_thumb__2PWVn に
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
max-height: 100px;
のstyle足すと期待される表示になるとおもいます。
一つの解法として参考になれば。

**Comment by naari3** [comment]
@gokulin とても良さそうです！！ありがとうございます！！！！

#52 で修正される予定
![image](https://user-images.githubusercontent.com/12756563/100533389-161d0700-3247-11eb-9fa4-778ff081ea46.png)
