### ISSUE TITLE
開始日に1899年以前を指定すると502が返ってくる

### ISSUE THREAD

**Issue by ghost** [naari3/otomad-search#42]
# バグ内容
502が返ってきます
![image](https://user-images.githubusercontent.com/64119317/100495826-8e75c080-3192-11eb-9de2-ec06a33f63a5.png)

# 再現手順
開始日の年に1899以下の数字を指定する
![image](https://user-images.githubusercontent.com/64119317/100495887-0ba13580-3193-11eb-98cc-d52173767c7c.png)

なお、開始日が1900年以降で終了日が1899年以前の場合は発生しませんでした

**Comment by naari3** [comment]
@5h4ru たぶん修正しました thx 🙏
